### ISSUE TITLE
max() arg is an empty sequence error when generating rap

### ISSUE THREAD

**Issue by Fqlox** [robbiebarrat/rapping-neural-network#26]
Hi,
I got this error when I try to generate rap with my custom training data.

`Traceback (most recent call last):
  File "documented_model.py", line 412, in <module>
    main(depth, train_mode)
  File "documented_model.py", line 405, in main
    rap = vectors_into_song(vectors, bars, rhyme_list)
  File "documented_model.py", line 356, in vectors_into_song
    max_score = max(fixed_score_list)
ValueError: max() arg is an empty sequence`

Do you have an Idea of where it come from ?

Thanks in Advance.

**Comment by jwhollbush** [comment]
Same issue. I will check back and update if I find out what is going on.

**Comment by marinedanno** [comment]
Hello, have you found anything ? I also have the same issue. Thank you

**Comment by LeetCodes** [comment]
well, fuck, still nothing..?
